kind: Deployment
apiVersion: apps/v1
metadata:
   name: arnab
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: arnab
   template:
      metadata:
        labels:
          app: arnab
      spec:
       containers:
        - name: arnab
          image: krypto93/pipeline_demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80