kind: Deployment
apiVersion: apps/v1
metadata:
   name:  arnab biswas
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app:  arnab biswas
   template:
      metadata:
        labels:
          app:  arnab biswas
      spec:
       containers:
        - name:  arnab biswas
          image: krypto93/pipeline_demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80