kind: Service                             
apiVersion: v1
metadata:
  name: arnab
  labels:
    app: arnab
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: arnab                    
  type: LoadBalancer                   